### ISSUE TITLE
Comparison with the semver module

### ISSUE THREAD

**Issue by dandv** [quentinrossetti/version-sort#2]
The [semver package](https://www.npmjs.com/package/semver) already does [version comparison](https://docs.npmjs.com/misc/semver). How does this library compare to semver?

**Comment by quentinrossetti** [comment]
Interesting question. It would be great to test both modules on a large set of version.
I believe semver will be faster.
However I wrote this lib for sorting non-semver things (like "2.1" without PATCH number)

**Comment by yujingz** [comment]
yeah the biggest pain of semver is the lack of customization, you have to either completely accept major, minor, patch format or do some getter/setter thing to ignore the patch version.

also sometimes you'd want to use format like v1.01 instead of v1.1, semver doesn't let you do that
